core/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import Home,AboutPage,ServicePage,PageDetails,FaqList,EnquiryForm,Pricing,RegisterForm,Order,CreateCheckoutSession,CreateCheckoutSuccess,CreateCheckoutCancel,UserDashboard,UserProfileUpdate,UserOrderHistory

app_name = "main"
urlpatterns = [
    path('', Home,name="home"),
    path('page/<int:id>/', PageDetails,name="page"),
    path('about/', AboutPage,name="about"),
    path('services/', ServicePage,name="services"),
    path('faq/', FaqList,name="faq"),
    path('pricing/', Pricing,name="pricing"),
    path('checkout/<int:package_id>/', Order,name="order"),
    path('checkout-session/<int:package_id>/', CreateCheckoutSession,name="checkout-session"),
    path('success/', CreateCheckoutSuccess,name="checkout-success"),
    path('cancel/', CreateCheckoutCancel,name="checkout-success"),
    path('accounts/signup/', RegisterForm,name="register"),
    path('contact/', EnquiryForm,name="contact"),


    # User Dashboard Section
    path('account/user-dashboard/', UserDashboard, name="user-dashboard"),
    path('account/update-profile',UserProfileUpdate,name='update-profile'),
    path('account/order/', UserOrderHistory, name='order-history'),

]

templates/partials/header.html
 <div class="container">
        <div class="custom_nav2">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="d-flex  flex-column flex-lg-row align-items-center">
                <ul class="navbar-nav  ">
                  <li class="nav-item {% if request.path == '/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item {% if request.path == '/about/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:about' %}">About </a>
                  </li>
                  <li class="nav-item {% if request.path == '/services/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:services' %}">Services </a>
                  </li>
                  <li class="nav-item {% if request.path == '/pricing/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:pricing' %}">Pricing </a>
                  </li>
                  <li class="nav-item {% if request.path == '/contact/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:contact' %}">Contact Us</a>
                  </li>
                     {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                       {{user.username}}
                    </a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'main:user-dashboard' %}">Dashboard</a>
                      <a class="dropdown-item" href="{% url 'main:update-profile' %}">Profile</a>
                      <div class="dropdown-divider"></div>
                       <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                  </li>
                    {% else %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:register' %}">Register</a>
                  </li>
{% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                  <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                </form>
              </div>
            </div>
          </nav>
        </div>
      </div>

templates/partials/left-sidebar.html
<div class="list-group">
	<a href="{% url 'main:user-dashboard' %}" class="list-group-item {% if request.path == '/user-dashboard' %} active {% endif %}">Dashboard</a>
	<a href="{% url 'main:order-history' %}" class="list-group-item {% if request.path == '/order-history' %} active {% endif %}">Order History</a>
	<a href="{% url 'main:update-profile' %}" class="list-group-item {% if request.path == '/update-profile' %} active {% endif %}">Profile</a>
	<a href="{% url 'password_change' %}" class="list-group-item {% if request.path == '/accounts/password_change/' %} active {% endif %}">Change Password</a>
	<a href="{% url 'logout' %}" class="list-group-item">Logout</a>
</div>