core/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import Home,AboutPage,ServicePage,PageDetails,FaqList,EnquiryForm,Pricing,RegisterForm,Order,CreateCheckoutSession,CreateCheckoutSuccess,CreateCheckoutCancel,UserDashboard,UserProfileUpdate,UserOrderHistory

app_name = "main"
urlpatterns = [
    path('', Home,name="home"),
    path('page/<int:id>/', PageDetails,name="page"),
    path('about/', AboutPage,name="about"),
    path('services/', ServicePage,name="services"),
    path('faq/', FaqList,name="faq"),
    path('pricing/', Pricing,name="pricing"),
    path('checkout/<int:package_id>/', Order,name="order"),
    path('checkout-session/<int:package_id>/', CreateCheckoutSession,name="checkout-session"),
    path('success/', CreateCheckoutSuccess,name="checkout-success"),
    path('cancel/', CreateCheckoutCancel,name="checkout-success"),
    path('accounts/signup/', RegisterForm,name="register"),
    path('contact/', EnquiryForm,name="contact"),


    # User Dashboard Section
    path('account/user-dashboard/', UserDashboard, name="user-dashboard"),
    path('account/update-profile',UserProfileUpdate,name='update-profile'),
    path('account/order/', UserOrderHistory, name='order-history'),

]

main/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
# Create your models here.

# import a signal library
from django.db.models.signals import post_save
from django.dispatch import receiver



class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to='services/',null=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url) )


class Page(models.Model):
    title=models.CharField(max_length=150)
    detail = models.TextField()


    def __str__(self):
        return self.title

class Faq(models.Model):
    question=models.CharField(max_length=150)
    answer = models.TextField()


    def __str__(self):
        return self.question


class Enquiry(models.Model):
    full_name=models.CharField(max_length=150)
    email=models.EmailField(max_length=150)
    phone=models.CharField(max_length=150)
    message = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.full_name


class Package(models.Model):
    package_name = models.CharField(max_length=150,null=False)
    # description = models.TextField()
    price = models.PositiveIntegerField()
    max_member = models.PositiveIntegerField(null=True)
    highlight_status = models.BooleanField(default=False)

    def already_registered_members_count(self):
        return self.subscription_set.count()  # Assuming "subscription_set" is the related name

    def remaining_slots(self):
        if self.max_member is not None:
            registered_count = self.already_registered_members_count()
            remaining = max(0, self.max_member - registered_count)
            return remaining
        else:
            return None  # No maximum limit defined

    class Meta:
        verbose_name_plural ='Packages'

    def __str__(self):
        return self.package_name


class PackageFeatures(models.Model):
        package = models.ManyToManyField(Package, null=True)
        name = models.CharField(max_length=140)

        class Meta:
            verbose_name_plural = 'Package Details'



        def __str__(self):
            return f'{self.name}'


class PackageDiscount(models.Model):
    package = models.ForeignKey(Package,on_delete=models.CASCADE, null=True)
    total_months = models.PositiveIntegerField(default=0)
    total_discounts = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Package Discount'

    def __str__(self):
        return str(self.total_months)

class Subscriber(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    mobile = models.CharField(max_length=20)
    address = models.TextField()
    img = models.ImageField(upload_to='customer/', null=True)

    class Meta:
        verbose_name_plural = 'Customer'

    def __str__(self):
        return str(self.customer)

    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' % (self.img.url) )
        else:
            return 'no-image'


@receiver(post_save,sender=User)
def create_subscriber(sender,instance,created,**kwrags):
	if created:
		Subscriber.objects.create(customer=instance)

class Subscription(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    package = models.ForeignKey(Package,on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=60)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Order'

    def __str__(self):
        return str(self.package)

class SiteSettings(models.Model):
    site_logo = models.ImageField(upload_to='site_logo/')
    site_title = models.CharField(max_length=200)
    site_description = models.TextField()
    copyright_text = models.CharField(max_length=200)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=20)
    contact_address = models.CharField(max_length=50)

    def __str__(self):
        return self.site_title

    def logo(self):
        if self.site_logo:
            return mark_safe('<img src="%s" width="80" />' % (self.site_logo.url) )
        else:
            return 'no-image'

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from main.models import Enquiry

class EnquiryForm(forms.ModelForm):
    class Meta:
        model = Enquiry
        fields =('full_name','email','phone','message')

class SignUp(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email','username','password1', 'password2')

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ( 'username','first_name', 'last_name', 'email')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Exclude the password field from the form
        self.fields.pop('password')

        # Make the 'username' field readonly
        self.fields['username'].widget.attrs['readonly'] = True

main/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.template.loader import get_template
from main.models import Service,Page,Faq,Package,PackageFeatures,Subscription,SiteSettings
from . import forms
import stripe
from django.contrib.auth.decorators import login_required



# Create your views here.
def Home(request):
    context = {
        'setting': get_object_or_404(SiteSettings,pk=1),
        # 'banners' : Banner.objects.all(), # Banner.objects.filter()
        'services' : Service.objects.all().order_by("title")[:3],
        'about' : get_object_or_404(Page,pk=1),
        # 'galleries': Gallery.objects.all().order_by("title"),
    }
    return render(request,"main/home.html",context)

def AboutPage(request):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
    }
    return render(request, "main/about.html", context)

def ServicePage(request):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'services': Service.objects.all().order_by("title"),
    }
    return render(request, "main/services.html", context)

def PageDetails(request,id):
    context = {
        'setting': get_object_or_404(SiteSettings,pk=1),
        'page': get_object_or_404(Page, id=id),
    }
    return render(request, "main/page.html", context)

def FaqList(request):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'faqs': Faq.objects.all(),
        #'faq': get_object_or_404(Faq,),
    }
    return render(request, "main/faq.html", context)

def EnquiryForm(request):
    if request.method == 'POST':
        form = forms.EnquiryForm(request.POST)
        if form.is_valid():
            form.save()
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'form': forms.EnquiryForm(),
    }
    return render(request, "main/enquiry.html", context)


def Pricing(request):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'packages': Package.objects.all(),
        'features': PackageFeatures.objects.all(),
    }
    return render(request, "main/pricing.html", context)

def RegisterForm(request):
    message = None
    if request.method == 'POST':
        form = forms.SignUp(request.POST)
        if form.is_valid():
            form.save()
            message = 'Thank you for the Registration'
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'form': forms.SignUp,
        'message':message
    }
    return render(request, "main/register.html", context)


def Order(request,package_id):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'package_detail': get_object_or_404(Package,pk=package_id),
    }
    return render(request, "main/checkout.html", context)


stripe.api_key = 'sk_test_4eC39HqLyjWDarjtT1zdp7dc'
def CreateCheckoutSession(request,package_id):
 package = get_object_or_404(Package,pk=package_id)
 session = stripe.checkout.Session.create(
     line_items=[{
         'price_data': {
             'currency': 'usd',
             'product_data': {
                 'name': package.package_name,
             },
             'unit_amount': package.price*100,
         },
         'quantity': 1,
     }],
     mode='payment',
     success_url='http://127.0.0.1:8000/success?session_id={CHECKOUT_SESSION_ID}',
     cancel_url='http://127.0.0.1:8000/cancel',
     client_reference_id = package_id
 )

 return redirect(session.url, code=303)

from django.core.mail import EmailMessage
@login_required
def CreateCheckoutSuccess(request):

    session_id = request.GET.get('session_id')
    session = stripe.checkout.Session.retrieve(session_id)
    package_id = session.client_reference_id
    package = get_object_or_404(Package, pk=package_id)
    user = request.user
    # customer = stripe.Customer.retrieve(session.customer)

    Subscription.objects.create(
        package=package,
        user=user,
        price=package.price,
    )
    subject = 'Order Email'
    html_content = get_template('main/orderemail.html').render({'title': package.package_name})
    from_email = 'idre172@gmail.com'

    msg = EmailMessage(subject, html_content, from_email, ['dev@yopmail.com'])
    msg.content_subtype = "html"  # Main content is now text/html
    msg.send()
    context ={
        'setting': get_object_or_404(SiteSettings, pk=1),
    }
    return render(request, "main/success.html",context)

@login_required
def CreateCheckoutCancel(request):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
    }
    return render(request, "main/cancel.html", context)

@login_required
def UserDashboard(request,):
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
    }
    return render(request, "user/dashboard.html", context)

@login_required
def UserProfileUpdate(request):
	msg=None
	if request.method=='POST':
		form=forms.ProfileForm(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			msg='Data has been saved'
	form=forms.ProfileForm(instance=request.user)
	return render(request, 'user/update-profile.html',{'form':form,'msg':msg})

@login_required
def UserOrderHistory(request):
    current_user = request.user
    context = {
        'setting': get_object_or_404(SiteSettings, pk=1),
        'packages': Package.objects.all(),
        'orders':Subscription.objects.filter(user=current_user)

    }
    return render(request, "user/order-history.html", context)

templates/main/about.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}About Page {{setting.site_title}} | {{setting.site_description}}{% endblock %}
{% block content %}
 <!-- about section -->
<section class=" position-relative">
    {% include 'partials/header.html' %}
    </section>
    <!-- end slider section -->
  </div>
 <!-- Header -->
  <section class="about_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          About {{setting.site_title}}
        </h2>
      </div>
      <div class="box">
        <div class="img-box">
          <img src="{{setting.site_logo.url}}" alt="{{setting.site_title}}">
        </div>
        <div class="detail-box">
          <p>
            Fitness First is a global gym chain known for its comprehensive fitness facilities, group fitness classes, personal training services, and nutrition support. They offer various membership options, focus on creating a clean and safe workout environment, and often host special events and challenges. Fitness First emphasizes community, well-being, and customized fitness solutions for individuals of all fitness levels.
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- end about section -->
{% endblock %}

templates/main/checkout.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Checkout {{setting.site_title}} | {{setting.site_description}}{% endblock %}
{% block content %}
<!-- about section -->
<section class=" position-relative">
    {% include 'partials/header.html' %}
    </section>
    <!-- end slider section -->
  </div>
 <!-- Header -->
 <!-- Main Start -->
    <section class="container my-4">
         <div class="heading_container">
    	<h2 class="text-center">Checkout </h2>
<!--        <p class="fs-500 text-center">plans that work for everyone</p>-->
 </div>
    </section>
  <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
				<table class="table table-bordered">
					<thead class="table-warning">
						<tr>
							<th>Plan</th>
							<th>Plan Detail</th>
							<th>Payment For</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<table class="table-bordered table">
									<tr>
										<th>Name</th>
										<td>{{package_detail.package_name}}</td>
									</tr>
									<tr>
										<th>Price</th>
										<td>${{package_detail.price}}</td>
									</tr>
									<tr>
										<th>Max Member</th>
										<td>{{package_detail.max_member}}</td>
									</tr>
									<tr>
										<th>Already Registered</th>
										<td>{{package_detail.already_registered_members_count}}</td>
									</tr>
									<tr>
										<th>Balance Seats</th>
										<td>{{package_detail.remaining_slots}}</td>
									</tr>
								</table>
							</td>
							<td>
								<ul class="list-unstyled">
					              {% for feature in package_detail.packagefeatures_set.all %}
                        <li>{{ feature.name }}</li>
                    {% endfor %}
					            </ul>
							</td>
							<td>
								<p>Master Credit, Card and Debit Card</p>
								<table class="table table-bordered">
									{% for discount in package_detail.packagediscount_set.all|dictsort:"total_months" %}
									<tr>
										<td><input data-planprice="{{package_detail.price}}" data-discount="{{ discount.total_discounts }}" type="radio" id="validity{{ discount.id }}" name="validity" class="select-validity" value="{{ discount.total_months }}" /></td>
										<th><label for="validity{{ discount.total_discounts }}">{{ discount.total_months }} Month</label></th>
										<td>{{ discount.total_discounts }}%</td>
									</tr>
									{% endfor %}
								</table>
							</td>
						</tr>
					</tbody>
					<tfoot class="table-info">
						<tr>
							<td></td>
							<th>Total Amount</th>
							<td><b>$<span class="totalAmount">{{package_detail.price}}</span></b></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td>
								<form method="post" action="{% url 'main:checkout-session' package_detail.id %}">
									{% csrf_token %}
									<input type="submit" value="Proceed to Payment" class="btn btn-primary" />
								</form>
							</td>
						</tr>
					</tfoot>
				</table>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
<script type="text/javascript">
	$(document).ready(function(){
		$(".select-validity").on('click',function(){
			var _planPrice=$(this).attr('data-planprice');
			var _planDisc=$(this).attr('data-discount');
			var _planValid=$(this).val();
			var _totalPrice=_planPrice*_planValid;
			if(_planDisc>0){
				var _discountedPrice=_totalPrice*_planDisc/100;
				_discountedPrice=_totalPrice-_discountedPrice;
			}else{
				var _discountedPrice=_totalPrice;
			}
			$(".totalAmount").text(_discountedPrice);
		});
	});
</script>
{% endblock %}

templates/main/gallery.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Gallery {{setting.site_title}} | {{setting.site_description}}{% endblock %}
{% block content %}
  <!-- Main Start -->
    <main>

		<!-- Testimonials -->
		<section class="container-fluid bg-light py-4 mt-5 border-top border-bottom">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
							<div class="gallery">
								{% for gallery in galleries %}
								<a data-lightbox="home-gallery" href="{{ gallery.img.url }}">
									<img src="{{ gallery.img.url }}" width="300" class="img-thumbnail" alt="{{gallery.title}}"></a>
								{% endfor %}
							</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Testimonials -->

    </main>
    <!-- End -->
{% endblock %}

templates/main/home.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Home Page {{setting.site_title}} | {{setting.site_description}}{% endblock %}
{% block content %}
<!-- slider section -->
    <section class=" slider_section position-relative">
    {% include 'partials/header.html' %}
      <div class="slider_container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="container">
                <div class="row">
                  <div class="col-lg-6 col-md-7 offset-md-6 offset-md-5">
                    <div class="detail-box">
                      <h2>
                        Get Your Body
                      </h2>
                      <h1>
                        Fitness Here
                      </h1>
                      <p>
                       Welcome to Fitness First, where your fitness journey begins! We're excited to introduce you to our gym and all the amazing opportunities it offers for achieving your fitness goals.
                      </p>
                      <div class="btn-box">
                        <a href="{% url 'main:contact'%}" class="btn-2">
                          Get A Quote
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end slider section -->
  </div>
 <!-- Header -->

  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          About {{setting.site_title}}
        </h2>
      </div>
      <div class="box">
        <div class="img-box">
          <img src="{{setting.site_logo.url}}" alt="{{setting.site_title}}">
        </div>
        <div class="detail-box">
          <p>
            Fitness First is a global gym chain known for its comprehensive fitness facilities, group fitness classes, personal training services, and nutrition support.
          </p>
          <a href="{% url 'main:about'%}">
            Read More
          </a>
        </div>
      </div>
    </div>
  </section>
  <!-- end about section -->

  <!-- service section -->

  <section class="service_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Our Services
        </h2>
      </div>
      <div class="service_container">
       {% for service in services %}
        <div class="box">
          <img src="{{service.img.url}}" alt="{{service.title}}">
          <h6 class="visible_heading">
            {{service.title}}
          </h6>
          <div class="link_box">

            <h6>
              {{service.title}}
            </h6>
             <p>{{service.detail|truncatechars:30}}</p>
          </div>
        </div>
{% endfor %}
      </div>
    </div>
  </section>

  <!-- end service section -->


  <!-- Us section -->

  <section class="us_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Why Choose Us
        </h2>
      </div>
      <div class="us_container">
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/u-1.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              QUALITY EQUIPMENT
            </h5>
            <p>
              ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/u-2.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              HEALTHY NUTRITION PLAN
            </h5>
            <p>
              ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/u-3.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              SHOWER SERVICE
            </h5>
            <p>
              ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/u-4.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              UNIQUE TO YOUR NEEDS
            </h5>
            <p>
              ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end us section -->


  <!-- client section -->

  <section class="client_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          What Says Our Customers
        </h2>
      </div>
      <div id="carouselExample2Indicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExample2Indicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExample2Indicators" data-slide-to="1"></li>
          <li data-target="#carouselExample2Indicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/client.png' %}" alt="">
              </div>
              <div class="detail-box">
                <h5>
                  Consectetur
                </h5>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                </p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/client.png' %}" alt="">
              </div>
              <div class="detail-box">
                <h5>
                  Consectetur
                </h5>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                </p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/client.png' %}" alt="">
              </div>
              <div class="detail-box">
                <h5>
                  Consectetur
                </h5>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>

  <!-- end client section -->

  <!-- result section -->

  <section class="result_section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6 px-0">
          <div class="img-box">
            <img src="{% static 'images/result-img.jpg'%}" alt="">
          </div>
        </div>
        <div class="col-lg-4 col-md-5">
          <div class="detail-box">
            <h2>
              BUILT TO BRING <br>
              BEST RESULTS
            </h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
              ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
            </p>
            <a href="">
              Get A Quote
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end result section -->


  <!-- contact section -->
  <section class="contact_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          <span>
            Get In Touch
          </span>
        </h2>
      </div>
      <div class="layout_padding2-top">
        <div class="row">
          <div class="col-md-8 mx-auto ">
            <form action="">
              <div class="contact_form-container">
                <div>
                  <div>
                    <input type="text" placeholder="Name" />
                  </div>
                  <div>
                    <input type="email" placeholder="Email" />
                  </div>
                  <div>
                    <input type="text" placeholder="Phone Number" />
                  </div>
                  <div class="mt-5">
                    <input type="text" placeholder="Message" />
                  </div>
                  <div class="mt-5">
                    <button type="submit">
                      Send
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>
  </section>
  <!-- end contact section -->



  <!-- Main Start -->
    <main style="display:none">
    	<!-- banner Start -->
    	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
		  <div class="carousel-inner">
			  {% for banner in banners %}
		    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
		      <img src="{{ banner.img.url}}" class="d-block w-100" alt="{{banner.alt_text}}">
		    </div>
			  {% endfor %}
		  </div>
		  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Previous</span>
		  </button>
		  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Next</span>
		  </button>
		</div>
		<!-- End Banner -->
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading">Services</h1>
			<div class="row">
				 {% for service in services %}
				<div class="col-md-4">
					<div class="card">
					  <img src="{{ service.img.url }}" class="card-img-top" alt="{{service.title}}">
					  <div class="card-body">
					    <h3 class="card-title">{{service.title}}</h3>
					    <p class="card-text">{{service.detail|truncatechars:30}}</p>
					    <a href="service.php" class="btn btn-primary">Read More</a>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->

		<!-- Testimonials -->
		<section class="container-fluid bg-light py-4 mt-5 border-top border-bottom">
			<div class="container">
				<div class="row">
					<div class="col-md-5">
							<h1 class="mb-4 section-heading">{{about.title}}</h1>
							<p class="lh-base">{{about.detail|truncatechars:225}}</p>
							<p><a href="{% url 'main:page' about.id %}" class="btn btn-info text-white">Read More</a></p>
					</div>
					<div class="col-md-6 offset-1">
							<h1 class="mb-4 section-heading">Gallery <a href="#" class="float-end btn btn-info text-white mt-2">View All</a></h1>
							<div class="gallery">
								{% for gallery in galleries %}
								<a data-lightbox="home-gallery" href="{{ gallery.img.url }}">
									<img src="{{ gallery.img.url }}" width="155" class="img-thumbnail" alt="{{gallery.title}}"></a>
								{% endfor %}
							</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Testimonials -->

    </main>
    <!-- End -->
{% endblock %}

templates/main/register.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Register {{setting.site_title}} | {{setting.site_description}}{% endblock %}
{% block content %}
<!-- about section -->
<section class=" position-relative">
    {% include 'partials/header.html' %}
    </section>
<!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Register</h1>
			<div class="row">
				<div class="col-md-6 offset-3">
					{% if not request.user.is_authenticated %}
					{% if message %}
					<p>{{message}}</p>
					{% endif %}
					<form method="post" action=".">
						{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
							<tr>
								<td colspan="2">
									If Already register Please <a href="{% url 'login' %}">Login</a>
								</td>
							</tr>
						</table>
					</form>
				{% else %}
<p>Already Login in {{user.username}}</p>
<a href="{% url 'main:home' %}">Back to Home</a>
{% endif %}
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->

{% endblock %}