core/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import Home,AboutPage,ServicePage,PageDetails,FaqList,EnquiryForm,Pricing,RegisterForm,Order,CreateCheckoutSession,CreateCheckoutSuccess,CreateCheckoutCancel,UserDashboard,UserProfileUpdate,UserOrderHistory

app_name = "main"
urlpatterns = [
    path('', Home,name="home"),
    path('page/<int:id>/', PageDetails,name="page"),
    path('about/', AboutPage,name="about"),
    path('services/', ServicePage,name="services"),
    path('faq/', FaqList,name="faq"),
    path('pricing/', Pricing,name="pricing"),
    path('checkout/<int:package_id>/', Order,name="order"),
    path('checkout-session/<int:package_id>/', CreateCheckoutSession,name="checkout-session"),
    path('success/', CreateCheckoutSuccess,name="checkout-success"),
    path('cancel/', CreateCheckoutCancel,name="checkout-success"),
    path('accounts/signup/', RegisterForm,name="register"),
    path('contact/', EnquiryForm,name="contact"),


    # User Dashboard Section
    path('account/user-dashboard/', UserDashboard, name="user-dashboard"),
    path('account/update-profile',UserProfileUpdate,name='update-profile'),
    path('account/order/', UserOrderHistory, name='order-history'),

]

templates/layouts/base.html
{% load static %}
{% load tz %}
<!doctype html>
<html lang="en">
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan|Dosis:400,600,700|Poppins:400,600,700&display=swap"
    rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  </head>
  <body>
  {% if request.path == "/" %}
  <div class="hero_area">
    {% endif %}
    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <a class="navbar-brand" href="{% url 'main:home' %}">
            <img src="{{setting.site_logo.url}}" alt="{{setting.site_title}}" />
          </a>
          <div class="contact_nav" id="">
            <ul class="navbar-nav ">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <img src="{% static 'images/location.png' %}" alt="{{setting.site_title}}" />
                  <span>{{setting.contact_address}}</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <img src="{% static 'images/call.png' %}" alt="{{setting.site_title}}" />
                  <span>Call : {{setting.contact_phone}}</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <img src="{% static 'images/envelope.png' %}" alt="{{setting.site_title}}" />
                  <span>{{setting.contact_email}}</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </div>

    </header>
    <!-- end header section -->

    {% block content %}

    {% endblock %}

    <!-- info section -->

  <section class="info_section layout_padding2-top">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h6>
            About {{setting.site_title}}
          </h6>
          <p>
            {{setting.site_description}}
          </p>
        </div>
        <div class="col-md-2 offset-md-1">
          <h6>
            Menus
          </h6>
          <ul>
            <li class=" active">
              <a class="" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="">
              <a class="" href="{% url 'main:about'%}">About </a>
            </li>
            <li class="">
              <a class="" href="{% url 'main:services'%}">Services </a>
            </li>
            <li class="">
              <a class="" href="{% url 'main:pricing'%}">Services </a>
            </li>
            <li class="">
              <a class="" href="{% url 'main:contact'%}">Contact Us</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="">
              <a class="" href="{% url 'login'%}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>

        <div class="col-md-3">
          <h6>
            Contact Us
          </h6>
          <div class="info_link-box">
            <a href="#">
              <img src="images/location-white.png" alt="">
              <span> {{setting.contact_address}}</span>
            </a>
            <a href="tel:{{setting.contact_phone}}">
              <img src="images/call-white.png" alt="">
              <span>{{setting.contact_phone}}</span>
            </a>
            <a href="mailto:{{setting.contact_email}}">
              <img src="images/mail-white.png" alt="">
              <span> {{setting.contact_email}}</span>
            </a>
          </div>
          <div class="info_social">
            <div>
              <a href="">
                <img src="images/facebook-logo-button.png" alt="">
              </a>
            </div>
            <div>
              <a href="">
                <img src="images/twitter-logo-button.png" alt="">
              </a>
            </div>
            <div>
              <a href="">
                <img src="images/linkedin.png" alt="">
              </a>
            </div>
            <div>
              <a href="">
                <img src="images/instagram.png" alt="">
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

<!-- footer section -->
  <section class="container-fluid footer_section ">
   <div class="container">
	   <div class="row">
		   <div class="col-md-6">
			    <p>
                  {% if setting.copyright_text %}
                  {{setting.copyright_text}}
                  {% else %}
             &copy; {% now "Y" as current_year %} All Rights Reserved.
                  {% endif %}
    </p>
		   </div>
		   <div class="col-md-6 text-end">
			   <p><a href="{% url 'main:page' 2 %}">Privacy</a> ·
            <a href="{% url 'main:page' 3 %}">Terms</a> .
            <a href="{% url 'main:faq' %}">FAQ</a></p>
		   </div>
	   </div>
   </div>
  </section>
  <!-- footer section -->
 <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

  <script>
    function openNav() {
      document.getElementById("myNav").classList.toggle("menu_width");
      document
        .querySelector(".custom_menu-btn")
        .classList.toggle("menu_btn-style");
    }
  </script>
</body>

</html>